[supervisord]
nodaemon=false
logfile=/root/workspace/supervisord.log
pidfile=/tmp/supervisord.pid

[program:collbomber]
command=python3 -u /root/workspace/collbomber_bot.py
directory=/root/workspace
autostart=true
autorestart=true
startretries=999
startsecs=5
stderr_logfile=/root/workspace/bot_error.log
stdout_logfile=/root/workspace/bot_output.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
